services:
  db:
    image: postgis/postgis:18-3.6
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    networks:
    - postgres-network
    volumes:
      - type: bind
        source: ./db
        target: /postgres
    env_file:
      - local.env

  property-fetcher:
    build: ./property-fetcher
    networks:
    - postgres-network
    depends_on:
      - db
  
  journey-planner:
    build: ./journey-planner
    networks:
    - postgres-network
    depends_on:
      - db
  
  api:
    build: ./api
    restart: always
    networks:
    - postgres-network
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - local.env
    
networks:
  postgres-network:
    driver: bridge
